Contact form
cloud007bond/Portfolio pull request #3
Opened 2023-06-13 18:46 UTC by cloud007bond

- Added contact form in index.html
- Added contact page in styles.css
- Added an active button

2023-06-13 19:08 UTC, Tufahel requested changes
# Status: Required Changes :recycle:
Hi @cloud007bond & @Kwamay :wave:  

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🌟

![Alt Text](https://c.tenor.com/vOLW_UQMySIAAAAC/almost-there.gif)

✔️ Descriptive pull request.
✔️ Follow the correct GitHub flow.
✔️ Commit messages are meaningful.
✔️ Form submission is working fine.

## Required Changes ♻️

***Please kindly check the comments/review below.***

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 19:08 UTC, Tufahel commented on index.html
> +                  <textarea name="user_msg" id="message" name="message" cols="30" rows="10" maxlength="500" placeholder="Write your message here" required></textarea>
![image](https://github.com/cloud007bond/Portfolio/assets/60083437/6eef744b-3154-4451-a8c2-a05d01de5876)

- [ ] According to the given design guideline `p` and `input` fields should be centered so that the same margin for the right and left sides is justified.  Kindly fix this issue.

2023-06-13 19:08 UTC, Tufahel commented on index.html
> +         <hr class="end-line">
![image](https://github.com/cloud007bond/Portfolio/assets/60083437/dbd5b565-78fd-45c4-ac2d-76f38ee75873)

- [ ] I can see there is an extra `underline` which is not part of the original design. Kindly fix this issue.

2023-06-13 19:08 UTC, Tufahel commented on styles.css
> +
- Your Design: 
![image](https://github.com/cloud007bond/Portfolio/assets/60083437/dcd13871-ca5d-465d-9386-7d3a0d049155)

- Given Design:
![image](https://github.com/cloud007bond/Portfolio/assets/60083437/501e3f60-215a-4b4a-86bf-eef25156e465)

- [ ] Kindly compare both design and fix the position of the icons in background images to match the given design.

2023-06-14 16:19 UTC, osamaashraf6 requested changes
Hi @cloud007bond 😊, 

Good job so far!
There are some issues that you still need to work on from the previous reviewer to go to the next project but you are almost there!
![SoCloseAlmostGIF (3)](https://github.com/Graceshiks/Portfolio-MobileFirst/assets/83360636/42e92e8b-3a1d-4ba7-8cf7-86c4d258ee97)

## Highlights 🎉🎉

- [ ] Following Figma design😊👌
- [ ] All input fields are wrapped in a single-form element🚀💯
- [ ] All input fields have the required attribute to activate the validation on submission.👌
- [ ] Nice design .🚀


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 16:19 UTC, osamaashraf6 commented on index.html
>  </body>
- [ ] Kindly as stated by the previous reviewer 😃, Kindly compare both design and fix the position of the icons in background images to match the given design, as you see here most of the background image of this footer is hidden, so please try to place it at the correct position to stick to the Figma Design 💯🚀

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Original design | Your design| 
| --- | --- |
|  ![image](https://github.com/cloud007bond/Portfolio/assets/83360636/b35636dd-1688-4af2-a640-811c471d8c4a)  |    ![image](https://github.com/cloud007bond/Portfolio/assets/83360636/3a528d63-489c-4fd3-9b9c-e98223cee84a) |



| Figma design | Your design| 
| --- | --- |
|    ![image](https://github.com/cloud007bond/Portfolio/assets/83360636/8bd19c7b-2d14-40cd-90ec-cabb4067b861)  |   ![image](https://github.com/cloud007bond/Portfolio/assets/83360636/4ba91cc6-207b-429e-9098-6be3c82028dd)    |

2023-06-14 17:56 UTC, victorokoroji approved these changes
Hi @cloud007bond, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- Requested changes implemented✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 19:02 UTC, merged

2023-06-15 08:26 UTC, binyamolango commented
Hi @cloud007bond,

Such a great project. Just as a friendly advice, I would suggest writing your commits in the future in the present tense as instruction; like "Add . . . Update . . .". This way your commits can give a precise meaning to the reader.

2023-06-16 19:49 UTC, Titus-Kiplagat commented
Hi @cloud007bond 
Great job! Developing the project design but there are some optional suggestions I would like you to consider:
- [ ] [Optional] Additionally,  I've reviewed your code and overall, it looks great! However, I noticed a few areas where you could improve the HTML structure by avoiding the use of irrelevant div tags. Consider the following suggestions:
- I would recommend avoiding the irrelevant `<div>` tag in the form section with the class `form-items`. Removing the `<div>` tag and updating the `<form>` tag with the class `form-items` will do the job.